services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      TZ: Africa/Johannesburg
      HOMEPAGE_ALLOWED_HOSTS: "localhost:3000,g500:3000,192.168.0.248:3000,100.70.229.32:3000"

    volumes:
      - /home/wandile/homelab/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - homelab

  files:
    image: appflowyinc/files:latest
    container_name: files
    restart: unless-stopped

    ports:
      - "8082:8080"

    volumes:
      - /mnt/storage:/data/storage
      - /home/wandile/Thehdd:/data/thehdd
      - /home/wandile/homelab:/data/homelab

    networks:
      - homelab

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/wandile/homelab/config/portainer:/data

    networks:
      - homelab

networks:
  homelab:
    external: true
